### ISSUE TITLE
Istio / Envoy JWK Refresh

### ISSUE THREAD

**Issue by maennchen** [caos/zitadel#2041]
**Describe the bug**

Istio / Envoy refreshes the JWKs in an interval. This interval seems not to line up with the Zitadel Key Rotation.

**To Reproduce**

1. Install Istio
1. Create K8S Resources

<details>

<summary><code>AuthorizationPolicy</code></summary>

```yml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: xyz
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals:
              - '*'
      to:
        - operation:
            paths:
              - '*'
  selector:
    matchLabels:
      #...
```

</details>
<details>

<summary><code>RequestAuthentication</code></summary>

```yml
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: xyz
spec:
  jwtRules:
    - audiences:
        # - ...
      forwardOriginalToken: true
      fromHeaders:
        - name: Authorization
          prefix: 'Bearer '
      fromParams:
        - authorization
      issuer: 'https://issuer.zitadel.aich
      jwksUri: 'https://api.zitadel.ch/oauth/v2/keys'
      outputPayloadToHeader: x-jwt-claims
  selector:
    matchLabels:
      #...
```

</details>

1. Wait
2. Make a new request
3. Results in 403 `unknown kid`

**Expected behavior**
Keys are refreshed correctly.

**Additional context**

* https://github.com/istio/istio/pull/30014
* https://github.com/istio/istio/blob/master/pilot/pkg/model/jwks_resolver.go

I tried to figure out if Istio or Zitadel is not adhering to the specification. As far as I found, the specification does not talk about refresh / caching at all. (https://datatracker.ietf.org/doc/html/rfc7517)
